"""
Run Protenix for antibody structure prediction.

Protenix is an open-source implementation of AlphaFold 3 by ByteDance:
https://github.com/bytedance/Protenix

Attribution:
Protenix Team et al. (2026). Protenix-v1: Toward High-Accuracy Open-Source
Biomolecular Structure Prediction. bioRxiv.
https://doi.org/10.64898/2026.02.05.703733

License: Apache 2.0
"""

import subprocess
import os
import json
import shutil
import numpy as np
import pandas as pd

from typing import Union, List
from Bio import PDB


def _unwrap(val):
    """Unwrap Protenix's single-element list serialization.

    Protenix's ``save_json`` converts tensors via ``.tolist()``.  A shape-[1]
    tensor becomes ``[value]`` and shape-[1, N] becomes ``[[v0, v1, ...]]``.
    This helper normalises both cases so downstream code receives plain
    scalars or 1-D lists, matching what the AF3 pipeline expects.
    """
    if isinstance(val, list) and len(val) == 1 and isinstance(val[0], list):
        return val[0]          # [[v0, v1, ...]] → [v0, v1, ...]
    if isinstance(val, list) and len(val) == 1:
        return val[0]          # [value] → value
    return val


def create_protenix_input(
    binder_seq: str,
    target_seq: Union[str, List[str]],
    binder_chain: str,
    target_chains: Union[str, List[str]],
    design_name: str,
    msa_paths: dict = None,
) -> list:
    """
    Create input JSON data for Protenix inference.

    Protenix uses a different JSON schema from AF3: sequences are specified as
    'proteinChain' entries (not 'protein' with chain IDs). Input is a list of
    job dicts.

    Args:
        binder_seq (str): Amino acid sequence of the binder protein.
        target_seq (Union[str, List[str]]): Amino acid sequence(s) of the target.
        binder_chain (str): Chain ID for the binder protein.
        target_chains (Union[str, List[str]]): Chain ID(s) for the target.
        design_name (str): Name identifier for this design.
        msa_paths (dict): Optional mapping of chain IDs to absolute MSA file paths.

    Returns:
        list: Protenix-compatible input JSON (list of one job dict).
    """
    if isinstance(target_chains, str):
        target_chains = target_chains.split(",")
    if isinstance(target_seq, str):
        target_seq = [target_seq]
    if msa_paths is None:
        msa_paths = {}

    sequences = []

    # Add target chains first (so target is chain A, etc.)
    for i, chain_id in enumerate(target_chains):
        target_entry = {"proteinChain": {"sequence": target_seq[i], "count": 1}}
        if chain_id in msa_paths:
            target_entry["proteinChain"]["unpairedMsaPath"] = msa_paths[chain_id]
        sequences.append(target_entry)

    # Add binder chain after target(s).
    # Always provide an unpairedMsaPath for the binder -- even if it's just the
    # binder sequence itself (single-sequence A3M).  This prevents Protenix from
    # triggering its expensive remote MSA server search (~3 min), which fires
    # whenever ANY chain lacks an MSA path.  For de novo designed antibodies
    # there are no real homologs anyway, so a single-sequence MSA is correct.
    binder_entry = {"proteinChain": {"sequence": binder_seq, "count": 1}}
    if binder_chain in msa_paths:
        binder_entry["proteinChain"]["unpairedMsaPath"] = msa_paths[binder_chain]
    elif msa_paths:
        # Create a minimal single-sequence A3M for the binder so Protenix
        # won't trigger its remote MSA search for the whole job.
        # Place it next to the existing target MSA files.
        any_msa_path = next(iter(msa_paths.values()))
        binder_msa_dir = os.path.dirname(any_msa_path)
        binder_msa_path = os.path.join(binder_msa_dir, f"binder_{design_name}.a3m")
        with open(binder_msa_path, "w") as f:
            f.write(f">binder\n{binder_seq}\n")
        binder_entry["proteinChain"]["unpairedMsaPath"] = os.path.abspath(
            binder_msa_path
        )
    sequences.append(binder_entry)

    job = {
        "name": design_name,
        "sequences": sequences,
    }

    return [job]


def _get_or_generate_msas(
    target_seqs: List[str],
    target_chains: List[str],
    binder_seq: str,
    binder_chain: str,
    output_dir: str,
    msa_mode: str,
    run_settings: dict,
) -> dict:
    """
    Get existing MSAs or generate new ones for Protenix.

    Checks for MSAs previously generated by AF3 pipeline. If not found,
    generates new MSAs using ColabFold infrastructure.

    Args:
        target_seqs: Target protein sequences.
        target_chains: Target chain IDs.
        binder_seq: Binder protein sequence.
        binder_chain: Binder chain ID.
        output_dir: Base directory for MSA storage.
        msa_mode: MSA generation mode ("local", "colabfold", "target", "none").
        run_settings: Configuration with MSA database paths.

    Returns:
        dict: Mapping of chain IDs to absolute MSA file paths.
    """
    from germinal.filters.af3 import (
        generate_local_msa,
        call_generate_colabfold_msa_with_timeout,
    )

    msa_paths = {}
    msa_dir = os.path.join(output_dir, "protenix_inputs")
    os.makedirs(os.path.join(msa_dir, "msas"), exist_ok=True)

    for i, chain_id in enumerate(target_chains):
        design_name_msa = f"target_{chain_id}"
        msa_filename = f"msas/{design_name_msa}.a3m"

        # Check existing locations (protenix or af3 inputs)
        for base_dir in [msa_dir, os.path.join(output_dir, "af3_inputs")]:
            existing = os.path.join(base_dir, msa_filename)
            if os.path.exists(existing):
                msa_paths[chain_id] = os.path.abspath(existing)
                break

        if chain_id in msa_paths:
            continue

        # Generate MSA for this target chain
        sequence = target_seqs[i]
        if msa_mode == "local":
            rel_path = generate_local_msa(
                sequence,
                design_name_msa,
                msa_dir,
                run_settings["msa_db_dir"],
                use_metagenomic_db=run_settings.get("use_metagenomic_db", False),
            )
        elif msa_mode in ["colabfold", "target"]:
            rel_path = call_generate_colabfold_msa_with_timeout(
                sequence,
                design_name_msa,
                msa_dir,
                use_metagenomic_db=run_settings.get("use_metagenomic_db", False),
            )
        else:
            continue

        if rel_path:
            full_path = os.path.join(msa_dir, rel_path)
            if os.path.exists(full_path):
                msa_paths[chain_id] = os.path.abspath(full_path)

    return msa_paths


def extract_protenix_scores(
    output_dir: str,
    design_name: str,
    binder_chain_idx: int = 0,
    select_mode: str = "best",
) -> tuple:
    """
    Extract predicted structure and confidence scores from Protenix output.

    Converts the best/worst CIF output to PDB format and extracts confidence
    metrics in a format compatible with the AF3 output dict used by the
    filter pipeline.

    Args:
        output_dir (str): Directory containing Protenix output.
        design_name (str): Name identifier for the design.
        binder_chain_idx (int): Index of the binder chain (0-based).
        select_mode (str): "best" or "worst" based on ranking_score.

    Returns:
        tuple: (pdb_path, scores_dict, ipsae) matching run_af3 return format.
    """
    results_folder = os.path.join(output_dir, design_name)

    # Find all summary confidence files across all seeds/samples
    confidence_files = []
    for root, dirs, files in os.walk(results_folder):
        for f in files:
            if "summary_confidence" in f and f.endswith(".json"):
                confidence_files.append(os.path.join(root, f))

    if not confidence_files:
        raise FileNotFoundError(
            f"No summary confidence files found in {results_folder}"
        )

    # Select best/worst sample based on ranking_score
    best_score = None
    best_confidence_path = None
    best_cif_path = None
    best_full_data_path = None

    for conf_path in confidence_files:
        with open(conf_path, "r") as f:
            conf = json.load(f)
        score = conf.get("ranking_score", 0)
        is_better = (
            (best_score is None)
            or (select_mode == "best" and score > best_score)
            or (select_mode == "worst" and score < best_score)
        )

        if is_better:
            best_score = score
            best_confidence_path = conf_path
            # Derive CIF path: replace _summary_confidence_ with _
            cif_name = os.path.basename(conf_path).replace(
                "_summary_confidence_", "_"
            ).replace(".json", ".cif")
            best_cif_path = os.path.join(os.path.dirname(conf_path), cif_name)
            # Derive full data path: replace _summary_confidence_ with _full_data_
            full_data_name = os.path.basename(conf_path).replace(
                "_summary_confidence_", "_full_data_"
            )
            best_full_data_path = os.path.join(
                os.path.dirname(conf_path), full_data_name
            )

    if best_cif_path is None or not os.path.exists(best_cif_path):
        raise FileNotFoundError(
            f"Best CIF file not found. Looked for: {best_cif_path}"
        )

    # Convert CIF to PDB
    pdb_path = os.path.join(output_dir, f"{design_name}_protenix.pdb")
    parser = PDB.MMCIFParser(QUIET=True)
    io_pdb = PDB.PDBIO()
    structure = parser.get_structure("structure", best_cif_path)
    io_pdb.set_structure(structure)
    io_pdb.save(pdb_path)

    # Read summary confidence
    with open(best_confidence_path, "r") as f:
        summary = json.load(f)

    # ---- Build scores dict compatible with AF3 output format ----
    scores = {}

    # pLDDT - Protenix summary "plddt" is 0-100 scale (atom_plddt.mean()*100);
    # normalize to 0-1 to match AF3 scores dict convention.
    scores["plddt"] = np.float64(_unwrap(summary.get("plddt", 0))) / 100.0
    # chain_plddt is already 0-1 scale (averaged from atom_plddt without *100)
    chain_plddt = _unwrap(summary.get("chain_plddt", []))
    if len(chain_plddt) > binder_chain_idx:
        scores["plddt_binder"] = np.float64(chain_plddt[binder_chain_idx])
    else:
        scores["plddt_binder"] = scores["plddt"]

    # PAE matrix from full data if available
    pae_matrix = np.array([[0.0]])
    token_asym_id = np.array([0])
    full_data = {}
    if best_full_data_path and os.path.exists(best_full_data_path):
        with open(best_full_data_path, "r") as f:
            full_data = json.load(f)
        if "token_pair_pae" in full_data:
            pae_matrix = np.array(full_data["token_pair_pae"])
        if "token_asym_id" in full_data:
            token_asym_id = np.array(full_data["token_asym_id"])

    scores["pae_matrix"] = pae_matrix
    scores["pae"] = np.mean(pae_matrix) if pae_matrix.size > 1 else np.float64(0.0)

    # Binder PAE (PAE within binder chain)
    if pae_matrix.size > 1 and token_asym_id.size > 1:
        binder_mask = token_asym_id == binder_chain_idx
        if binder_mask.any():
            binder_pae = pae_matrix[np.ix_(binder_mask, binder_mask)]
            scores["binder_pae"] = np.mean(binder_pae)
        else:
            scores["binder_pae"] = np.float64(0.0)
    else:
        scores["binder_pae"] = np.float64(0.0)

    # Chain pair PAE min - use chain_pair_gpde as approximation
    chain_pair_gpde = _unwrap(summary.get("chain_pair_gpde", [[0.0]]))
    scores["chain_pair_pae_min"] = np.array(chain_pair_gpde)

    # pTM and iPTM
    scores["ptm"] = [_unwrap(summary.get("ptm", 0.0))]
    scores["iptm"] = [_unwrap(summary.get("iptm", 0.0))]
    scores["chain_iptm"] = np.array(_unwrap(summary.get("chain_iptm", [0.0])))
    scores["chain_ptm"] = np.array(_unwrap(summary.get("chain_ptm", [0.0])))
    scores["aggregate_score"] = [_unwrap(summary.get("ranking_score", 0.0))]

    # ipSAE - create AF3-compatible JSON from Protenix data so the ipsae tool
    # can parse it.  The ipsae tool detects CIF+JSON as "af3" format and
    # expects keys "atom_plddts" (0-100 scale) and "pae" (token-level NxN).
    # Protenix's full_data uses "atom_plddt" (0-1 scale) and "token_pair_pae".
    # NOTE: need_atom_confidence defaults to True in Protenix >= v1.0.0
    # (configs_inference.py), so full_data files are written automatically.
    ipsae = None
    try:
        has_full_data = (
            best_full_data_path
            and os.path.exists(best_full_data_path)
            and pae_matrix.size > 1
        )
        if has_full_data:
            # atom_plddt lives in the full_data JSON (already loaded above)
            atom_plddt_raw = full_data.get("atom_plddt", [])

            if len(atom_plddt_raw) > 0:
                # Build AF3-compatible JSON: convert plddt 0-1 → 0-100 scale
                af3_compat = {
                    "atom_plddts": (np.array(atom_plddt_raw) * 100.0).tolist(),
                    "pae": pae_matrix.tolist(),
                }
                af3_compat_path = best_full_data_path + ".af3compat.json"
                with open(af3_compat_path, "w") as f:
                    json.dump(af3_compat, f)
                # Also create a summary_confidences file so ipsae can find
                # global scores (it looks for a file with "summary_confidences"
                # in the name, but Protenix uses "summary_confidence").
                summary_compat_path = af3_compat_path.replace(
                    "full_data", "summary_confidences"
                )
                summary_compat = {
                    "chain_pair_iptm": summary.get("chain_pair_iptm", []),
                }
                with open(summary_compat_path, "w") as f:
                    json.dump(summary_compat, f)

                result = subprocess.run(
                    ["ipsae", af3_compat_path, best_cif_path, "10", "10"],
                    capture_output=True,
                    text=True,
                )
                if result.returncode != 0:
                    print(f"ipsae tool stderr: {result.stderr}")

                # Clean up temp files
                for tmp in [af3_compat_path, summary_compat_path]:
                    if os.path.exists(tmp):
                        os.remove(tmp)

                ipsae_out_file = os.path.join(
                    os.path.dirname(os.path.abspath(best_cif_path)),
                    os.path.basename(best_cif_path).replace(".cif", "_10_10.txt"),
                )
                if os.path.exists(ipsae_out_file):
                    df = pd.read_csv(ipsae_out_file, delim_whitespace=True)
                    ipsae = {
                        "ipsae": df["ipSAE"].iloc[-1],
                        "pdockq2": df["pDockQ2"].iloc[-1],
                        "LIS": df["LIS"].iloc[-1],
                    }
                else:
                    print("ipSAE output file not found after running ipsae tool")
            else:
                print("ipSAE skipped: atom_plddt not found in full_data")
        else:
            print(
                f"ipSAE skipped: full_data exists={has_full_data}, "
                f"pae_matrix size={pae_matrix.size}"
            )
    except Exception as e:
        print(f"ipSAE calculation failed for Protenix output: {e}")

    # Clean up Protenix results folder to save disk space
    shutil.rmtree(results_folder, ignore_errors=True)

    return pdb_path, scores, ipsae


def _run_protenix(
    input_json: list,
    output_dir: str,
    binder_chain_idx: int,
    seeds: list,
    run_settings: dict,
    select_mode: str = "best",
) -> tuple:
    """
    Execute Protenix structure prediction via subprocess in a conda environment.

    Args:
        input_json (list): Protenix-compatible input JSON (list of job dicts).
        output_dir (str): Directory to save prediction outputs.
        binder_chain_idx (int): Index of the binder chain (0-based).
        seeds (list): List of random seeds for inference.
        run_settings (dict): Configuration dict containing:
            - protenix_conda_env: conda environment name (default: "protenix")
            - protenix_model_name: model checkpoint (default: "protenix_base_default_v1.0.0")
        select_mode (str): "best" or "worst" for sample selection.

    Returns:
        tuple: (pdb_path, scores_dict, ipsae)
    """
    os.makedirs(output_dir, exist_ok=True)

    # Write input JSON
    input_dir = os.path.join(output_dir, "protenix_inputs")
    os.makedirs(input_dir, exist_ok=True)
    design_name = input_json[0]["name"]
    input_path = os.path.join(input_dir, f"{design_name}.json")
    with open(input_path, "w") as f:
        json.dump(input_json, f, indent=2)

    # Build Protenix command.
    # need_atom_confidence defaults to True in Protenix >= v1.0.0, so
    # full_data files (PAE matrix) are written automatically.
    conda_env = run_settings.get("protenix_conda_env", "protenix")
    model_name = run_settings.get(
        "protenix_model_name", "protenix_base_default_v1.0.0"
    )
    seeds_str = ",".join(str(s) for s in seeds)

    # Protenix inference speed settings (configurable via YAML):
    #   protenix_use_msa:  Whether to run Protenix's built-in MSA search.
    #       Setting to False saves ~3 min per call (biggest bottleneck).
    #       Pre-computed MSAs in the JSON (unpairedMsaPath) are still used.
    #   protenix_samples:  Number of diffusion samples per seed (default 5).
    #       Reducing to 1 speeds up inference with minimal quality loss.
    #   protenix_cycles:   Pairformer cycles (default 10).
    #       Reducing to 3-5 speeds up the forward pass.
    #   protenix_steps:    Diffusion steps (default 200).
    #       Reducing to 50-100 speeds up sampling.
    use_msa = run_settings.get("protenix_use_msa", True)
    n_samples = run_settings.get("protenix_samples", 5)
    n_cycles = run_settings.get("protenix_cycles", 10)
    n_steps = run_settings.get("protenix_steps", 200)

    run_cmds = [
        "conda", "run", "-n", conda_env, "--no-capture-output",
        "protenix", "pred",
        "-i", input_path,
        "-o", str(output_dir),
        "-s", seeds_str,
        "-n", model_name,
        "-e", str(n_samples),
        "-c", str(n_cycles),
        "-p", str(n_steps),
        "--use_msa", str(use_msa),
    ]

    print(f"Running Protenix: {' '.join(run_cmds)}")

    popen = subprocess.Popen(
        run_cmds,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )
    _, stderr_data = popen.communicate()
    return_code = popen.returncode

    if return_code:
        if stderr_data:
            print(f"Protenix stderr:\n{stderr_data}")
        raise subprocess.CalledProcessError(return_code, run_cmds)

    pdb_path, scores, ipsae = extract_protenix_scores(
        output_dir, design_name, binder_chain_idx, select_mode
    )

    return pdb_path, scores, ipsae


def run_protenix(
    binder_seq: str,
    target_seq: Union[str, List[str]],
    target_chains: Union[List[str], str],
    output_dir: str,
    design_name: str,
    seed: Union[int, List[int]],
    run_settings: dict,
    binder_chain: str = "B",
    msa_mode: str = "none",
    select_mode: str = "best",
) -> tuple:
    """
    Run Protenix structure prediction for antibody-target complex.

    High-level interface matching run_af3() signature for drop-in use.

    Args:
        binder_seq (str): Amino acid sequence of the antibody binder.
        target_seq (Union[str, List[str]]): Amino acid sequence(s) of the target.
        target_chains (Union[List[str], str]): Chain identifier(s) for target.
        output_dir (str): Directory to save prediction outputs.
        design_name (str): Unique identifier for this design.
        seed (Union[int, List[int]]): Random seed(s) for reproducible predictions.
        run_settings (dict): Configuration dict. Protenix-specific keys:
            - protenix_conda_env: conda env name (default: "protenix")
            - protenix_model_name: model checkpoint name
              (default: "protenix_base_default_v1.0.0")
        binder_chain (str): Chain ID for binder protein. Defaults to 'B'.
        msa_mode (str): MSA generation method ('none', 'local', 'colabfold',
            'target'). Defaults to 'none'.
        select_mode (str): Which sample to extract ('best' or 'worst').
            Defaults to 'best'.

    Returns:
        tuple: (pdb_path, scores_dict, ipsae) where:
            - pdb_path (str): Path to predicted complex structure (PDB format)
            - scores_dict (dict): Confidence metrics compatible with AF3 format
            - ipsae (dict or None): ipSAE, pDockQ2, and LIS scores if available
    """
    if isinstance(seed, int):
        seed = [seed]
    if isinstance(target_chains, str):
        target_chains = target_chains.split(",")
    if isinstance(target_seq, str):
        target_seq = [target_seq]

    # Handle MSA generation / reuse
    msa_paths = {}
    if msa_mode in ["local", "colabfold", "target"]:
        msa_paths = _get_or_generate_msas(
            target_seq,
            target_chains,
            binder_seq,
            binder_chain,
            output_dir,
            msa_mode,
            run_settings,
        )

    # Create Protenix input JSON
    input_json = create_protenix_input(
        binder_seq, target_seq, binder_chain, target_chains, design_name, msa_paths
    )

    # Binder comes after target chain(s) in the input ordering
    binder_chain_idx = len(target_chains)

    return _run_protenix(
        input_json,
        output_dir,
        binder_chain_idx=binder_chain_idx,
        seeds=seed,
        run_settings=run_settings,
        select_mode=select_mode,
    )
